- name: run insights to obtain latest diagnosis info
  hosts: "@@HOSTS@@"
  become: True
  tasks:
    - name: obtain diagnosis info
      command: 'insights-client --diagnosis@@REMEDIATION@@'
      register: insights_result
      changed_when: false
      check_mode: false
    - name: register insights report as fact for use by other plays
      set_fact: insights_report={{ insights_result.stdout }}
