- name: run insights to obtain latest diagnosis info
  hosts: "@@HOSTS@@"
  vars:
    insights_remediation: "@@REMEDIATION@@"
    insights_signature_exclude: "/hosts,/vars/insights_remediation"
  become: True
  tasks:
    - name: obtain diagnosis info
      command: "insights-client --diagnosis{{ insights_remediation | regex_search('\\s[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') }}"
      register: insights_result
      changed_when: false
      check_mode: false
    - name: register insights report as fact for use by other plays
      set_fact: insights_report={{ insights_result.stdout }}
