- name: run insights
  hosts: "@@HOSTS@@"
  vars:
    insights_signature_exclude: "/hosts"
  become: True
  gather_facts: False
  tasks:
    - name: run insights
      command: insights-client
      changed_when: false
