- name: service_autofs_disabled
  hosts: '@@HOSTS@@'
  become: true
  tags:
  - NIST-800-53-AC-19(e)
  - NIST-800-53-IA-3
  - DISA-STIG-RHEL-07-020110
  - medium_severity
  - service_autofs_disabled
  - CCE-27498-5
  - NIST-800-53-AC-19(d)
  - disable_strategy
  - NIST-800-53-AC-19(a)
  - low_disruption
  - NIST-800-171-3.4.6
  - low_complexity
  tasks:
  - name: Disable service autofs
    service:
      name: autofs
      enabled: 'no'
      state: stopped
    register: service_result
    failed_when: service_result is failed and ('Could not find the requested service'
      not in service_result.msg)
  - name: Disable socket of service autofs if applicable
    service:
      name: autofs.socket
      enabled: 'no'
      state: stopped
    register: socket_result
    failed_when: socket_result is failed and ('Could not find the requested service'
      not in socket_result.msg)
