{{ if .Values.deploy.remediations }}
---
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  name: view-mnm
roleRef:
  name: {{ .Values.prometheusRole | default "view" }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.prometheusNamespace | default "mnm" }}
userNames:
- system:serviceaccount:{{ .Values.prometheusNamespace | default "mnm" }}:default
{{ end }}
