deploy:
  redis: true
  postgres: true
  cac: true
  remediations: true
  ssg: true

imageRegistry: docker-registry.default.svc:5000
imageNamespace: buildfactory

prometheusRole: edit
prometheusNamespace: mnm-ci

remediations:
  # Command to use for db migration. In stable environments this should be "npm run db:create; npm run db:migrate"
  migrationCommand: "npm run db:init && npm run db:migrate && npm run db:seed"

  logLevel: trace
  imageChangeTrigger: true

  advisor:
    impl: impl
    host: http://insights-advisor-api.advisor-qa.svc.cluster.local:8000
  contentServer:
    host: http://content-server.advisor-qa.svc.cluster.local:8080
  vulnerabilities:
    impl: impl
    host: http://vulnerability-engine-manager.vulnerability-engine-qa.svc.cluster.local:8443
  compliance:
    impl: impl
    host: http://compliance-backend.compliance-qa.svc.cluster.local:3000
  cac:
    impl: impl
    host: http://playbooks-cac:8080
  inventory:
    impl: impl
    host: http://insights-inventory.platform-qa.svc.cluster.local:8080
  users:
    impl: impl
    host: https://insights-services-pipeline-insights.ext.paas.redhat.com

ssg: {}

secrets:
  backoffice: false
  postgres: false
  redis: false
